[package]
name = "samsa"
version = "0.1.0"
edition = "2021"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-stream = "0.3.5"
bytes = { version = "1.5.0", features = ["serde"] }
claim = "0.5.0"
crc = "3.0.1"
dotenvy = "0.15.7"
dotenvy_macro = "0.15.7"
futures = "0.3.30"
nom = "7.1.3"
nombytes = "0.1.1"
num-derive = "0.4.2"
num-traits = "0.2.18"
sentiment = "0.1.1"
serde = { version = "1.0.196", features = ['derive'] }
serde_json = "1.0.113"
tokio = { version = "1.36.0", features = ['full'] }
tokio-stream = "0.1.14"
tracing = "0.1.37"
tracing-subscriber = "0.3.17"

[dev-dependencies]
criterion = "0.3"

[[bench]]
name = "parser"
harness = false

[[bench]]
name = "encoder"
harness = false

[features]
integration_tests = []
