name: Release
on:
  push:
    tags:
    - '*'

env:
  CARGO_TERM_COLOR: always
  RUST_VERSION: 1.76.0

jobs:
    publish:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v3
        - name: rustup
          run: rustup default $RUST_VERSION
        - name: publish
          run: cargo publish --token ${secrets.CARGO_REGISTRY_TOKEN}