name: Rust
on: 
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:  

env:
  CARGO_TERM_COLOR: always
  RUST_VERSION: 1.76.0

jobs:
  static_analysis:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: rustup
        run: rustup default $RUST_VERSION
      - name: cargo-fmt
        run: rustup component add rustfmt && cargo fmt --check
      - name: cargo-clippy
        run: rustup component add clippy && cargo clippy --all-targets --all-features -- --no-deps -D warnings

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: rustup
      run: rustup default $RUST_VERSION
    - name: build
      run: make
    - name: test
      run: make check
